### PR TITLE
Add keymap file for Linux

### PR DESCRIPTION
**Pull request by konoknir**
Fix key mapping on Linux

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
`Default.sublime-keymap` covers Linux already, are you hitting an issue?

**Comment by konoknir** [comment]
I don't know how i did hit an issue but I can't reproduce it anymore, so I think we can close it for now :)

**Comment by ryanpcmcquen** [comment]
@konoknir, I probably broke something, thanks for contributing!

**Comment by konoknir** [comment]
Nah, I don't think so. It was probably because of the original plugin remainings or something. I can't thank you enough for making this plugin finally working with the new versions of php and xdebug. Well done, sir!

**Comment by ryanpcmcquen** [comment]
Happy to help, @konoknir, if you don't mind, upvote the Package Control PR so we can make installation easier. 😉

https://github.com/wbond/package_control_channel/pull/7658

**Comment by konoknir** [comment]
Will do

**Pull request closed without merging**
